server:
  port: ${SERVER_PORT}

logging:
  level:
    root: warn
    me.sonam.authzmanager: info
#    org.springframework.web: info
#    org.springframework.security: info
#    org.springframework.security.oauth2: info
#    org.springframework.boot.autoconfigure: warn

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  application:
    name: authzmanager
  thymeleaf:
    cache: false
#  r2dbc:
#    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
#    username: ${POSTGRES_USERNAME}
#    password: ${POSTGRES_PASSWORD}
#    properties:
#      sslMode: ${DB_SSLMODE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          audiences: ${OAUTH_AUDIENCES}

permitpath:
  - path: /authzmanager/api/health/*

jwtrequest:
  - in:  /*
    out: /authenticate
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}

user-rest-service:
  root: ${USER_REST_SERVICE}
  signup: /signup

# this is used for getting accesstoken by header filter in jwt-validator (ReactiveRequestContextHolder.class)
auth-server:
  root: ${AUTH_SERVER}
  clients: /clients
  authenticate: /myauthenticate
  oauth2token:
    path: /oauth2/token
    params: ?grant_type=client_credentials

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}/authentications
  authenticate: /authenticate

allowedOrigins: ${allowedOrigins}

