# Base application configuration for tenant-aware authzmanager routing.
server:
  port: ${SERVER_PORT}

logging:
  level:
    root: warn
    me.sonam: debug
    me.sonam.authzmanager.tokenfilter: debug

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  main:
    allow-bean-definition-overriding: true
  application:
    name: authzmanager
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf: # to enable hot reload of Thymeleaf templates
    cache: false


permitpath:
  - path: /authzmanager/api/health/*

requestFilters:
  - out:
    outHttpMethods:
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}

# this is used for getting accesstoken by header filter in jwt-validator (ReactiveRequestContextHolder.class)
auth-server:
  root: ${AUTH_SERVER}
  contextPath:
  clients: /clients
#  clientOrganizations: /clients
  authenticate: /authenticate
  oauth2token:
    path: /oauth2/token
    grantType: client_credentials

user-rest-service:
  root: ${USER_REST_SERVICE}
  context: /users
  photo: /photo

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}/authentications
  authenticate: /authenticate

organization-rest-service:
  root: ${ORGANIZATION_REST_SERVICE}
  contextPath: /organizations

role-rest-service:
  root: ${ROLE_REST_SERVICE}
  contextPath: /roles

account-rest-service:
  root: ${ACCOUNT_REST_SERVICE}
  context: ${account-rest-service.root}/accounts
  accountDelete: ${account-rest-service.context}/delete

allowedOrigins: ${allowedOrigins}

oauthClientId: authzmanager-client

issuerUri: ${ISSUER_URI}

authzmanager:
  oauth2:
    registration-id: b4dfe3fb-1692-44b8-92ab-366ccc84b539-authzmanager
    client-id: b4dfe3fb-1692-44b8-92ab-366ccc84b539-authzmanager
    client-secret: ${AUTHZMANAGER_INITIAL_SECRET}
    prepend-uuid-to-created-client-id: true
    prepend-uuid-to-created-client-id-hosts: ${AUTHZMANAGER_OAUTH2_PREPEND_UUID_TO_CREATED_CLIENT_ID_HOSTS:}
  tenancy:
    host-label: admin
  user-search:
    hosts:
      free.openissuer.com:
        allowed-email-domains:
          - "*"
      business1.openissuer.com:
        allowed-email-domains:
          - business1.com
      business2.openissuer.com:
        allowed-email-domains:
          - business2.com

aws:
  s3:
    region: ${REGION}
    accessKeyId: ${ACCESS_KEY_ID}
    secretAccessKey: ${SECRET_ACCESS_KEY}
    bucket: sonam
    endpoint: ${ENDPOINT}
    subdomain: ${SUBDOMAIN}
    rootPath: authzmanager/
    videoPath: videos/
    photoPath: photos/
    filePath: files/
    imageAclHeader: x-amz-acl
    imageAclValue: public-read
    presignDurationInMinutes: 60
    thumbnailSize:
      width: 200
      height: 200

profilePhotoFolder: profile/
tokenExpireSeconds: 180

maxClients: 5
maxOrganizations: 1
maxUserPerOrganization: 5
maxRoles: 5
maxUsersPerOrganization: 10
