server:
  port: ${SERVER_PORT}

logging:
  level:
    root: warn
    me.sonam: debug
    me.sonam.authzmanager.tokenfilter: error

#    me.sonam.authzmanager: info
#    me.sonam.authzmanager.tokenfilter: debug
#    org.springframework.web: info
#    org.springframework.security: info
#    org.springframework.security.oauth2: info
#    org.springframework.boot.autoconfigure: warn

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: authzmanager
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf: # to enable hot reload of Thymeleaf templates
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

permitpath:
  - path: /authzmanager/api/health/*

jwtrequest:
  - in:  /*
    out: /issuer/authenticate
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in:  /*
    out: /organizations
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in:  /*
    out: /users,/users/id/(.)*,/users/(.)*,/issuer/clients/(.)*,
        /issuer/clients,/issuer/clientOrganizations/clients/id/(.)*/organizations/id,
        /issuer/clientOrganizations,/issuer/clientOrganizations/clientId/(.)*/organizationId/(.)*,
        /issuer/clientOrganizations/findRow,/issuer/clientOrganizations/id/(.)*/organizationId/(.)*,
        /organizations,/organizations/(.)*,/organizations/(.)*/users/(.)*,/roles,/roles/organizations/(.)*,
        /roles/(.)*, /roles/organizations/(.)*
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}


user-rest-service:
  root: ${USER_REST_SERVICE}
  contextPath: /users

# this is used for getting accesstoken by header filter in jwt-validator (ReactiveRequestContextHolder.class)
auth-server:
  root: ${AUTH_SERVER}
  contextPath: /issuer
  clients: /clients
  clientOrganizations: /clients
  authenticate: /authenticate
  oauth2token:
    path: /oauth2/token
    grantType: client_credentials

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}/authentications
  authenticate: /authenticate

organization-rest-service:
  root: ${ORGANIZATION_REST_SERVICE}
  contextPath: /organizations

role-rest-service:
  root: ${ROLE_REST_SERVICE}
  contextPath: /roles


allowedOrigins: ${allowedOrigins}

oauthClientId: authzmanager-client