# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
SERVER_PORT: 9093

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: authzmanager
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

spring:
  cloud:
    kubernetes:
      enabled: false

USER_REST_SERVICE: http://user-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
AUTH_SERVER: http://authorization-server

allowedOrigins: http://api-gateway, 10.0.0.28, localhost, 127.0.0.1, api-gateway, 10.0.0.28:8080, 127.0.0.1