# Kubernetes profile values for tenant-aware authzmanager deployment.
# this profile is activated by kubernetes dependencies
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        namespaces:
           - backend
        include-not-ready-addresses: true
eureka:
  client:
      enabled: false

#internal naming used for service discovery

USER_REST_SERVICE: http://user-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
AUTH_SERVER: http://authorization-server
ORGANIZATION_REST_SERVICE: http://organization-rest-service
ROLE_REST_SERVICE: http://role-rest-service
ACCOUNT_REST_SERVICE: http://account-rest-service
SETTING_REST_SERVICE: http://setting-rest-service

allowedOrigins: https://api-gateway.sonam.cloud

ISSUER_ADDRESS: https://platform.openissuer.com

ISSUER_URI: ${ISSUER_ADDRESS}
OAUTH_AUDIENCES: oauth-client
