server:
  port: ${SERVER_PORT}

logging:
  level:
    root: trace
#    me.sonam.auth: info
#    org.springframework.web: info
#    org.springframework.security: info
#    org.springframework.security.oauth2: info
#    org.springframework.boot.autoconfigure: warn

spring:
  profiles:
    active: local
  application:
    name: authzmanager
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

permitpath:
  - path: /authzmanager/api/health/*
